### ISSUE TITLE
Documentation: Issues in installation instructions for Debian 11 "Bullseye" (at least)

### ISSUE THREAD

**Issue by 01100001** [weechat/weechat.org#107]
## Bug summary

Installation instructions at https://weechat.org/download/debian/ fail on Debian 11 "Bullseye" at least.

Issue starts with the required packages installation command provided `sudo apt-get install dirmngr gpg-agent apt-transport-https` as it doesn't install `gpg` itself.

Then the use of `--no-default-keyring` in the `sudo gpg ...` command that follows causes other errors due to it not allowing for the `/root/.gnupg/` directory to be created.

(Couldn't have identified the issues without the help of the kind folks on `#weechat` IRC channel.)

## Steps to reproduce

*(Simply following instructions at https://weechat.org/download/debian/ for Debian 11 "Bullseye" and applying fixes as necessary. Output of the commands is shown indented after each command—where necessary, for clarity.)*

Install required packages as per the documentation:

```
$ sudo apt-get install dirmngr gpg-agent apt-transport-https
```

Import the GPG key used to sign the repositories:

```
$ sudo mkdir -p /usr/local/share/keyrings

$ sudo gpg --no-default-keyring --keyring /usr/local/share/keyrings/weechat-archive-keyring.gpg --keyserver hkps://keys.openpgp.org --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E

    sudo: gpg: command not found
```

Install `gpg` to fix the issue of missing package:

```
$ sudo apt-get install gpg
```

Run the command to import the GPG key used to sign the repositories — again:

```
$ sudo gpg --no-default-keyring --keyring /usr/local/share/keyrings/weechat-archive-keyring.gpg --keyserver hkps://keys.openpgp.org --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E

    gpg: keybox '/usr/local/share/keyrings/weechat-archive-keyring.gpg' created
    gpg: failed to create temporary file '/root/.gnupg/.#lk0x000055ad529dc160.temp2.14929': No such file or directory
    gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
    gpg: keyserver receive failed: No dirmngr
```

It appears the `/root/.gnupg/` directory isn't being created automatically by `gpg` due to use of the `--no-default-keyring` flag.

## Current behavior

(See above. It's clearer if the output is shown with the commands so I added it above.)

## Expected behavior

Installation should be possible by simply following the instructions in the documentation.

## Suggested solutions

1.  Include `gpg` among the packages to install, along with any other recommended packages.

2.  Remove `--no-default-keyring` from the `sudo gpg` command.

    Alternatively, user should simply run `gpg` and exit it (<kbd>Ctrl</kbd> + <kbd>C</kbd>) for `/root/.gnupg/` directory to be created. Then the `sudo gpg` command, with the `--no-default-keyring` flag, should run without issues.

    User could, of course, also create it manually, like so:

    ```
    sudo mkdir /root/.gnupg
    sudo chown -R root:root /root/.gnupg/
    sudo chmod 700 /root/.gnupg/
    ```

## Additional information

N/A

---

- WeeChat version: N/A
- OS, distribution and version: Debian 11 "Bullseye"
- Terminal: N/A
- Terminal multiplexer (screen/tmux/…/none): N/A

**Comment by shurane** [comment]
Can something like how [nodesource](https://github.com/nodesource/distributions#manual-installation) or [vscode](https://code.visualstudio.com/docs/setup/linux) imports the GPG key be done here with weechat?

Also, isn't the path for trusted keyrings in `/usr/share/keyrings`, not `/usr/local/share/keyrings`?

**Comment by iam-TJ** [comment]
`/usr/share/keyrings/` is for 'system' package-manager installed whereas `/usr/local/share/keyrings/` would be the place for administrator installed additions; at least that is the usual convention for system-wide mixing that don't tread on each other.

**Comment by shurane** [comment]
It seems like `/use/share/keyrings` is preferred, at least according to [Debian docs](https://wiki.debian.org/DebianRepository/UseThirdParty). I guess it is not conclusive though. I do see a bunch of 3rd party repos like [riot.im](https://riot.im/download/desktop/) using that path instead of the /usr/local path.
