### ISSUE TITLE
Add support for ARM64 builds for raspbian

### ISSUE THREAD

**Issue by TheReptile** [weechat/weechat.org#108]
On Feb 2, Raspberry Pi OS 64 bit was officially released: https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/
It would be nice if WeeChat could supply official builds for arm64.
Right now when I add the raspbian repository, I get the following error:

```
W: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://weechat.org/raspbian bullseye InRelease' does not seem to provide it (sources.list entry misspelt?)
```

**Comment by flashcode** [comment]
Hi,

I moved the issue from weechat repository to this one: it's not a WeeChat issue, builds are completely separate from the project.

It's not really a weechat.org site issue as well, but better tracking the issue there.

**Comment by TheReptile** [comment]
This has been solved by Nils since July 30: https://weechat.org/raspbian/dists/bullseye/main/binary-arm64/
