### ISSUE TITLE
Add ARM Builds for Ubuntu

### ISSUE THREAD

**Issue by Techman** [weechat/weechat.org#109]
### Feature description

Right now, the [official Debian/Ubuntu repositories](https://weechat.org/download/debian/) only have ARM builds for Raspbian.

I would like to see this expanded to Ubuntu as well, at least for LTS releases. While I cannot speak for all, I and a few of my peers run WeeChat from servers. ARM has become a pretty compelling option in that space.

Recently I was looking to move my WeeChat install to an arm64 server running 22.04 LTS when I realized that there are no official packages for it.

**Comment by flashcode** [comment]
Hi,

First I moved this issue to weechat.org, the website providing Debian/Ubuntu/Raspbian builds (this is not part of WeeChat itself).

The short answer is: it's not planned (at least for now), detail below.

Currently it requires a lot of time and effort to maintain all these repositories:

- 31 chroots (18 active): 51 GB, must be updated regularly for security fixes and install new packages on rolling distros
- Debian/Ubuntu/Raspbian repositories: 6.5 GB

All chroots (except Raspbian, which is built on another server) are with arch amd64 or i386, so I can build all these packages on the same server.
Arch arm64 would require either another server or cross-compiling, which is harder, and I've not much time to invest and would require extra effort to maintain new repositories with different arch.

I built some repositories years ago to distribute WeeChat quickly for all these distro versions, but I think this is not my job (as a developer) to build packages and maintain repositories for so many distros / architectures.

This should be provided by distro maintainers:

- latest stable version as soon as they're released, for rolling releases like Debian unstable (currently 4.1.1 is availble in Debian unstable but 4.2.2 should be uploaded soon)
- latest stable version as backport for distributions already released / LTS (like Ubuntu 22.04): https://backports.debian.org/ and https://help.ubuntu.com/community/UbuntuBackports. Main advantage of backports is that they're available for all supported architectures of Debian and Ubuntu. This is currently lacking, and I can help any maintainer to build WeeChat on LTS distro versions if needed.

So I think you should ask to Ubuntu maintainer a backport of WeeChat on Ubuntu 22.04, or any other LTS you may need.

By the way, as an alternative to backports, you can still compile and install yourself, it's very easy once you've installed the required dependencies:

- compilation of sources: see the documentation: https://weechat.org/files/doc/weechat/stable/weechat_user.en.html#source_package
- build of Debian package, for example on Ubuntu 22.04:

```console
$ git checkout v4.2.2
$ ./tools/build_debian.sh 4.2.2-1 ubuntu/jammy
```
This applies some patches that could be required, according to your distro, and build all WeeChat packages automatically.

Hope that helps.

**Comment by Techman** [comment]
Reviewing this again since I upgraded to Ubuntu 24.04 over the weekend, but I wanted to ask: is there anything that would rule out the use of something like GitHub Actions to handle some of the work with building/providing releases?

I did check the Ubuntu repositories and there is no backport package available, at least at the time of this comment.

**Comment by flashcode** [comment]
Hi,

I added yesterday Debian repositories for Bookworm (stable) and Bullseye (oldstable), with arm64 and armhf architectures (Bullseye because it's still supported by Raspberry Pi OS, even if it's legacy).
These repositories will replace Raspbian ones that should be removed soon, they should work fine on Raspberry Pi.

For Ubuntu, I can add ARM builds on latest LTS (24.04), and according to https://help.ubuntu.com/community/SupportedArchitectures, only arm64 is supported, right?

**Comment by flashcode** [comment]
It seems armhf is also supported, as I can see it there: http://ports.ubuntu.com/dists/noble/main/

**Comment by flashcode** [comment]
I just added Ubuntu Noble arm64 repository, with for now WeeChat 4.4.1 (latest stable).

**Comment by flashcode** [comment]
@Techman, can we close this issue or armhf is really required as well?

**Comment by Techman** [comment]
Thank you! arm64 is sufficient. Sorry for the delayed response.
