### ISSUE TITLE
Broken link (404) ReleaseNotes-devel.html

### ISSUE THREAD

**Issue by runxiyu** [weechat/weechat.org#110]
https://www.weechat.org/files/doc/stable/weechat_user.en.html links to https://weechat.org/files/doc/weechat/ReleaseNotes-devel.html which is 404.

```html
<div class="paragraph">
<p>After an upgrade, it is <strong>strongly recommended</strong> to read the
<a href="[https://weechat.org/files/doc/weechat/ReleaseNotes-devel.html](view-source:https://weechat.org/files/doc/weechat/ReleaseNotes-devel.html)" target="_blank" rel="noopener">release notes <sup>↗</sup></a>
which contain important information about breaking changes and some
manual actions that could be required.</p>
</div>
```

**Comment by flashcode** [comment]
Hi,

Thanks for reporting!

There's a transition to markdown files that can be browsed directly on GitHub (this is done in weechat master branch, not in latest stable, ie 4.3.0).

So as a workaround, I've make these redirections:

- https://weechat.org/files/doc/weechat/ReleaseNotes-devel.html → https://github.com/weechat/weechat/blob/master/UPGRADING.md
- https://weechat.org/seb/weechat/doc/ChangeLog-devel.html → https://github.com/weechat/weechat/blob/master/CHANGELOG.md
