### ISSUE TITLE
Make the left topic bar collapsible (in the devel docs). 

### ISSUE THREAD

**Issue by absorber** [weechat/weechat.org#22]
Currently in the [devel docs](https://weechat.org/files/doc/devel/weechat_user.en.html) the topic bar is always there. See here - http://i.imgur.com/2OqdWoB.png

I personally (and I think lots of other people) enjoy it when the documentation can be read in full width, so could there please be a method to otherwise collapse that left bar?

**Comment by flashcode** [comment]
This problem should be reported in weechat repository, it's not about the website (the doc is generated using asciidoc by weechat itself, and the HTML result is just copied to weechat.org).
I'll look if it's easy to toggle the sidebar with asciidoc, but I'm not sure it's possible.
I can understand if people prefer to toggle it (or not have a sidebar at all), but I think it's better to have the sidebar to navigate (for now almost all feedbacks are positive on this sidebar).
