### ISSUE TITLE
Feature request: Run /who before /ban to know the $host variable

### ISSUE THREAD

**Issue by freijon** [weechat/weechat.org#27]
When running /ban \<nick\> for a user that has been in the channel before you, the $host variable in the setting irc.network.ban_mask_default is unknown to weechat which results in a fallback banmask $nick!*@*.
Weechat should run /who \<nick\> before /ban \<nick\> automatically.

**Comment by flashcode** [comment]
This is about WeeChat, not the site. Please submit in weechat repository.
So I close this issue.
