### ISSUE TITLE
Uses weak digest algorithm (SHA1) 

### ISSUE THREAD

**Issue by hinderaker** [weechat/weechat.org#51]
With Ubuntu 16.04 Xenial I get the following warning every time I use "apt-get update".

`W: https://weechat.org/ubuntu/dists/xenial/InRelease: Signature by key 11E9DE8848F2B65222AA75B8D1820DB22A11534E uses weak digest algorithm (SHA1)`

_PS! This is **NOT** a duplicate. The problem still exists and instead of opening it again in the wrong repository I created a new issue here._

**Comment by flashcode** [comment]
Sorry, I resigned all repositories, but it looks like xenial and yakkety were missing.
The problem should now be fixed in all repositories (including xenial).

**Comment by hinderaker** [comment]
Confirmed, now it is working at intended.
