### ISSUE TITLE
Script name field on script submission form has maxlength limit of 64 but the text after it says "max 20 chars"

### ISSUE THREAD

**Issue by tomoe-mami** [weechat/weechat.org#53]
Since there are [scripts like this][1] that have 21 chars name, I assume the "max 20 chars" text is the incorrect one. This minor inconsistency might confuse new script authors.

[1]: https://weechat.org/scripts/source/bitlbee_typing_notice.py.html/

EDIT: Ah, just tried submitting and there's server side checking that *does* check if script name is longer than 20 chars. How did bitlbee_typing_notice.py and correction_completion.py get accepted then?

I think the limit should be increased to 32 chars. 20 is too short.

So I guess this is both bug report (inconsistency between server side check and client side check) and feature request (increase limit to 32 chars).

**Comment by flashcode** [comment]
I have set a limit to 20 chars, which should be enough for a script name. Some old scripts may have more than 20 chars if they were accepted before I set this limit, so this is not a bug.

**Comment by tomoe-mami** [comment]
So the 20 chars limit is final? :disappointed:

If so then may be the attribute should be updated. [It's still 64](http://i.imgur.com/zmbJRnf.png). I'd make a PR If I know how Django template works. I tried searching "maxlength", but found no results.

**Comment by flashcode** [comment]
Hi,
I increased the max length for script name to 32.
If you want to rename the pending script (nickcompletewrapper.lua), please give me the new name.

**Comment by tomoe-mami** [comment]
Thank you :) The original name is nick_complete_wrapper.lua. Easier to read with underscores so just use that one.

**Comment by flashcode** [comment]
Done, if needed I'll update the link to your source (in your github repo).

**Comment by tomoe-mami** [comment]
Yes, the link in comment needs to be updated too. I've reverted the script in my repo to use _ again.
