### ISSUE TITLE
Correction for German website version

### ISSUE THREAD

**Issue by zilti** [weechat/weechat.org#56]
The plural of "Skript" is "Skripte", NOT "Skripten". It's eyecancer-inducing.

**Comment by flashcode** [comment]
Hi,

I'll check that with @weechatter (he's doing German translations) and if needed fix that on weechat.org and WeeChat itself.

**Comment by weechatter** [comment]
Duden says: das Skript; Genitiv: des Skript[e]s, Plural: die Skripte[n] und Skripts

**Comment by zilti** [comment]
...and also states it is (luckily) hardly ever used. Because it's painful to read.

**Comment by zilti** [comment]
Really though, "Skripten" is just painfully wrong in most casus.

**Comment by weechatter** [comment]
I still believe in Duden.

**Comment by zilti** [comment]
As I said, it's a matter of casus. The overview page of the Duden doesn't mention this, because that's not what it is for. See also https://de.wikipedia.org/wiki/Skriptsprache.

**Comment by weechatter** [comment]
"Skripten" is not wrong! Lot of articels using this:

http://comptips.info/de/pages/304056
https://wiki.ubuntuusers.de/Shell/Bash-Skripting-Guide_f%C3%BCr_Anf%C3%A4nger/
https://raspberry.tips/raspberrypi-einsteiger/raspberry-pi-autostart-von-skripten-und-programmen-einrichten/
https://www.administrator.de/wissen/regelm%C3%A4%C3%9Figer-aufruf-programmen-skripten-anderen-befehlen-131008.html
http://scratch-dach.info/wiki/Debuggen_von_Skripten
or in the book "Matlab für Dummies"
...
...

I am sorry if you don't like it, but this is your personal preference as you wrote in your first message. 
Now i am closing this issue.

**Comment by zilti** [comment]
Did you even spend one hour of your life in a German lesson? Apparently not.
