### ISSUE TITLE
Suggestion: Better documentation for "/server add server hostname"

### ISSUE THREAD

**Issue by berndbausch** [weechat/weechat.org#79]
It might be obvious for people who have been using IRC, but a total newbie like me is quite confused by [this line in the quick start guide](https://weechat.org/files/doc/stable/weechat_quickstart.en.html#add_irc_server):

> /server add \<server\> \<hostname\>[/\<port\>]

I spent 15 minutes wondering and searching the internet to understand the meanings of _server_ versus _hostname_. When I see \<server\>, I think "hostname of a server". So, why enter the server name twice?

Later, it dawned to me that \<server\> is not an attribute of the IRC server, and that I can replace it with any string I want. E.g. after `/server alberteinstein chat.freenode.net`, I can access the freenode IRC server with `/connect alberteinstein`.

Would be nice if this were documented somewhere, especially in the quickstart document.

**Comment by weechatter** [comment]
Well, there is also a /help server with examples:

/server add chatspike irc.chatspike.net/6667,irc.duckspike.net/6667 
/server add freenode chat.freenode.net/6697 -ssl -autoconnect

and in the /help for the <server> and <hostname> arguments:
server: server name, for internal and display use
hostname: name or IP address of server, with optional port (default: 6667), many addresses can be separated by a comma

I don't know how to make it *more* clearer. Any suggestions!?

**Comment by flashcode** [comment]
I'll update the quickstart guide and `/help server` to explicit the difference between the server name and hostname (and rename arguments in the command help).

**Comment by flashcode** [comment]
By the way this is a weechat issue, not weechat.org site. Please open the issue in weechat repository, I'm closing this one.

**Comment by berndbausch** [comment]
Can I still comment? Yes, Nils (weechatter) is right of course. However, this is a "first steps" page and attracts people like me :) A one-liner would be sufficient to clarify this.

**Comment by flashcode** [comment]
@berndbausch: done via 2 commits: https://github.com/weechat/weechat/commit/70892bf71cc5cd088c25119a7807f26738497af1 and https://github.com/weechat/weechat/commit/974c25df76172d689a3beb93a5e9f5cf5dc482de
Is that OK for you now?
