### ISSUE TITLE
Long script name causes weird wrapping

### ISSUE THREAD

**Issue by sim642** [weechat/weechat.org#82]
The longest script name gnome_screensaver_away.py causes weird wrapping in the scripts table name column. If that row didn't exist, the same issue would happen with whatever other longest script name there is, etc. See screenshot:
![screenshot-2018-6-23 weechat scripts](https://user-images.githubusercontent.com/378740/41807302-d8565a86-76d5-11e8-9992-541cfb43c9b0.png)

I think popular stars should be in a separate column, not a float because that non-existent popular icon is causing it to wrap like that.

**Comment by flashcode** [comment]
Thanks for reporting, fixed.
