### ISSUE TITLE
make signing key available on weechat.org with an url

### ISSUE THREAD

**Issue by weechatter** [weechat/weechat.org#87]
for example with: https://weechat.org/dev/info/signing_key

initial task is to use it with Travis

**Comment by haavard** [comment]
Note that the key required for Travis is the WeeChat Debian Repository key, i.e. `11E9DE8848F2B65222AA75B8D1820DB22A11534E`, and not the regular signing key.

**Comment by weechatter** [comment]
also https://weechat.org/dev/info/fingerprint would be fine :-)

**Comment by flashcode** [comment]
Implemented: 5eab9b4df989e30f9ccd3f7274c1dcb9547c783d.
