### ISSUE TITLE
Do not use SKS for distributing weechat signing key

### ISSUE THREAD

**Issue by dngray** [weechat/weechat.org#97]
Hi,

The weechat signing key is being spammed, the instructions on https://weechat.org/download/ should **not** use the SKS network, users attempting the instruction to import the key will break their gnupg installation.

Currently the signing key on SKS is 180MB.

Background:
- https://dkg.fifthhorseman.net/blog/openpgp-certificate-flooding.html
- https://dkg.fifthhorseman.net/blog/community-impact-openpgp-cert-flooding.html
- https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f
- https://lists.gnupg.org/pipermail/gnupg-announce/2019q3/000439.html

**Comment by flashcode** [comment]
Fixed, thanks for pointing the problem.
